/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tung.chuong2;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 56745654242453456656
 */
public class lab3bai8baitapmorong extends javax.swing.JFrame {
    ArrayList<SinhVien> danhSach = new ArrayList<>();

    DefaultTableModel model;

    SinhVien sinhVienDangChon = null;
    
    class SinhVien {

        String hoTen;
        String maSV;
        int soMon;
        double diemTB;

        SinhVien(String hoTen, String maSV, int soMon, double diemTB) {
            this.hoTen = hoTen;
            this.maSV = maSV;
            this.soMon = soMon;
            this.diemTB = diemTB;
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lab3bai8baitapmorong.class.getName());

    /**
     * Creates new form lab3bai8baitapmorong
     */
    public lab3bai8baitapmorong() {
        initComponents();
        model = (DefaultTableModel) jb1.getModel();

        model.setColumnIdentifiers(
                new Object[]{
                    "Ten sinh vien",
                    "Ma sv",
                    "So mon",
                    "Diem TB"
                }
        );
    }
    private void hienThiDanhSach() {

        model.setRowCount(0);

        for (SinhVien sv : danhSach) {

            model.addRow(new Object[]{
                sv.hoTen,
                sv.maSV,
                sv.soMon,
                String.format("%.2f", sv.diemTB)
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tsl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jb1 = new javax.swing.JTable();
        tmsv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tht = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btt = new javax.swing.JButton();
        bts = new javax.swing.JButton();
        btx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SO LUONG MON");

        tsl.addActionListener(this::tslActionPerformed);

        jb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ten sinh vien", "Ma sv", "So mon", "Diem TB"
            }
        ));
        jScrollPane1.setViewportView(jb1);

        jLabel2.setText("MA SV");

        jLabel3.setText("Ho Va Ten");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("QUAN LY DIEM SINH VIEN");

        btt.setText("Them");
        btt.addActionListener(this::bttActionPerformed);

        bts.setText("Sua");

        btx.setText("xoa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btt)
                                .addGap(33, 33, 33)
                                .addComponent(bts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btx))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tmsv, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(tsl)
                                    .addComponent(tht))))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(tmsv))
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btt)
                            .addComponent(bts)
                            .addComponent(btx))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tslActionPerformed

    private void bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActionPerformed
        // TODO add your handling code here:
        String hoTen = tht.getText().trim();
        String maSV = tmsv.getText().trim();
        String soMonText = tsl.getText().trim();

        // Kiem tra thong tin
        if (hoTen.isEmpty()
                || maSV.isEmpty()
                || soMonText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui long nhap day du thong tin!"
            );

            return;
        }

        int soMon;

        try {

            soMon = Integer.parseInt(soMonText);

            if (soMon <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "So luong mon phai lon hon 0!"
                );

                return;
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "So luong mon phai la so!"
            );

            return;
        }

        // Kiem tra trung ma sinh vien
        for (SinhVien sv : danhSach) {

            if (sv.maSV.equalsIgnoreCase(maSV)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Ma sinh vien da ton tai!"
                );

                return;
            }
        }

        /*
     * Nhap diem cho N mon
         */
        double tongDiem = 0;

        for (int i = 1; i <= soMon; i++) {

            String diemCCText = JOptionPane.showInputDialog(
                    this,
                    "Nhap diem CC mon " + i + ":"
            );

            String diemGKText = JOptionPane.showInputDialog(
                    this,
                    "Nhap diem GK mon " + i + ":"
            );

            String diemCKText = JOptionPane.showInputDialog(
                    this,
                    "Nhap diem CK mon " + i + ":"
            );

            try {

                double cc = Double.parseDouble(diemCCText);
                double gk = Double.parseDouble(diemGKText);
                double ck = Double.parseDouble(diemCKText);

                if (cc < 0 || cc > 10
                        || gk < 0 || gk > 10
                        || ck < 0 || ck > 10) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Diem phai nam trong khoang 0 - 10!"
                    );

                    return;
                }

                // Cong thuc diem
                double diemMon
                        = cc * 0.20
                        + gk * 0.30
                        + ck * 0.50;

                tongDiem += diemMon;

            } catch (Exception e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Diem phai la so!"
                );

                return;
            }
        }

        // Tinh diem trung binh cac mon
        double diemTB = tongDiem / soMon;

        // Tao sinh vien
        SinhVien sv = new SinhVien(
                hoTen,
                maSV,
                soMon,
                diemTB
        );

        danhSach.add(sv);

        // Hien thi len JTable
        hienThiDanhSach();

        JOptionPane.showMessageDialog(
                this,
                "Them sinh vien thanh cong!"
        );
    }//GEN-LAST:event_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lab3bai8baitapmorong().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bts;
    private javax.swing.JButton btt;
    private javax.swing.JButton btx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jb1;
    private javax.swing.JTextField tht;
    private javax.swing.JTextField tmsv;
    private javax.swing.JTextField tsl;
    // End of variables declaration//GEN-END:variables
}
