/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tung.chuong2;
import javax.swing.*;
import javax.swing.SwingWorker;

/**
 *
 * @author 56745654242453456656
 */
public class lab4bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lab4bai3.class.getName());

    /**
     * Creates new form lab4bai3
     */
    public lab4bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tT = new javax.swing.JProgressBar();
        txtxt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txA = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap N");

        btinh.setText("Tinh");
        btinh.addActionListener(this::btinhActionPerformed);

        txA.setColumns(20);
        txA.setRows(5);
        jScrollPane2.setViewportView(txA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tT, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btinh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean soNT(int i) {
        if (i<2) {
            return false;
        }
        if (i==2) {
            return true;
        }
        if (i%2==0) {
            return false;
        }
        for (int n=3; n<=Math.sqrt(i);n+=2) {
            if (i%n==0) {
                return false;
            }
        }return true;
    }
    private void btinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinhActionPerformed
        // TODO add your handling code here:
        tinhTong();
    }//GEN-LAST:event_btinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lab4bai3().setVisible(true));
    }
    public void tinhTong(){
        int n;
        try {
            n = Integer.parseInt(txtxt1.getText().trim());
            if (n<=2) {
                JOptionPane.showMessageDialog(this, "N phai lon hon 2");
                return;
            }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui long nhap so hop le");
            return;
        }
        btinh.setEnabled(false);
        tT.setValue(0);
        jLabel2.setText("Dang tinh...");
        
        SwingWorker<Long, Void> worker = new SwingWorker<>() {
            @Override   
            protected Long doInBackground() {
                long sum = 0;
                for (int i = 2; i<n; i++) {
                    if (soNT(i)){
                        sum += i;
                    }
                    int tdo = (int) ((i*100.0)/n);
                    setProgress(tdo);
                }
                return sum;
            }
            @Override
            protected void done() {
                try {
                    long result = get();
                    jLabel2.setText("Tong cac so nguyen nho hon" + n +"="+result);
                }catch (Exception e){
                    jLabel2.setText("co loi khi tinh.");
                }
                btinh.setEnabled(true);
                tT.setValue(100);
            }
        };
        worker.addPropertyChangeListener(evt -> {
           if ("progress".equals(evt.getPropertyName())) {
               tT.setValue((int) evt.getNewValue());
           } 
        });
        worker.execute();
    }          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar tT;
    private javax.swing.JTextArea txA;
    private javax.swing.JTextField txtxt1;
    // End of variables declaration//GEN-END:variables
}
